steps:
  - id: npm-install
    name: node:18
    secretEnv: ['NPM_TOKEN']
    entrypoint: npm
    args: ['i', '--quiet', '--package-lock-only']

  - id: npm-ci
    name: node:18
    secretEnv: ['NPM_TOKEN']
    entrypoint: npm
    args: ['ci', '--quiet']

  - id: test-unit
    name: node:18
    secretEnv: ['NPM_TOKEN']
    entrypoint: npm
    args: ['test']

  - id: npm-publish
    name: 'gcr.io/$PROJECT_ID/cloudbuilders/npm:6.13.4'
    secretEnv: ['NPM_TOKEN']
    env:
      - 'TAG_NAME=$TAG_NAME'
      - '_PR_NUMBER=$_PR_NUMBER'

timeout: 10m

logsBucket: 'gs://$PROJECT_ID-primary-cloudbuild-logs'

tags:
  - 'backend'
  - 'npm'
  - 'nodejs'

availableSecrets:
  secretManager:
    - versionName: projects/145393225073/secrets/npm-token-publish/versions/latest
      env: NPM_TOKEN

